import { Summary } from '../types/summary.js';

/**
 * Generate a GitHub-formatted Pull Request description from a summary
 */
export function generatePRDescription(summary: Summary): string {
  let body = `## 🤖 AI Transformation Summary\n\n`;
  
  body += `### 📝 What Changed\n${summary.whatChanged}\n\n`;
  
  if (summary.whyChanged) {
    body += `### 🎯 Rationale\n${summary.whyChanged}\n\n`;
  }

  if (summary.howChanged) {
    body += `### 🛠️ Technical Implementation\n${summary.howChanged}\n\n`;
  }

  if (summary.filesChanged && summary.filesChanged.length > 0) {
    body += `### 📂 Files Modified\n`;
    summary.filesChanged.forEach(f => {
      const icon = f.action === 'created' ? '🆕' : f.action === 'deleted' ? '🗑️' : '📝';
      body += `- ${icon} \`${f.path}\`\n`;
    });
    body += '\n';
  }

  if (summary.decisions && summary.decisions.length > 0) {
    body += `### 💡 Key Decisions\n`;
    summary.decisions.forEach(d => {
      body += `- **${d.description}**${d.reason ? `: ${d.reason}` : ''}\n`;
    });
    body += '\n';
  }

  if (summary.blockers && summary.blockers.length > 0) {
    body += `### ⚠️ Blockers & Challenges\n`;
    summary.blockers.forEach(b => {
      const severityIcon = b.severity === 'critical' ? '🔴' : b.severity === 'error' ? '🟠' : '🟡';
      body += `- ${severityIcon} ${b.description}\n`;
    });
    body += '\n';
  }

  body += `---\n*Generated by [GLINR](https://github.com/GLINCKER/glinr-task-manager)*`;
  
  return body;
}

/**
 * Generate a release changelog from a collection of summaries
 */
export function generateChangelog(summaries: Summary[], version?: string): string {
  const date = new Date().toLocaleDateString();
  let changelog = `# Changelog - ${version || 'Unreleased'} (${date})\n\n`;

  // Group by type (if available) or by agent
  const groups: Record<string, Summary[]> = {};
  
  summaries.forEach(s => {
    const groupKey = s.taskType || s.agent || 'Other';
    if (!groups[groupKey]) groups[groupKey] = [];
    groups[groupKey].push(s);
  });

  for (const [groupName, groupSummaries] of Object.entries(groups)) {
    const formattedGroup = groupName.charAt(0).toUpperCase() + groupName.slice(1);
    changelog += `## ${formattedGroup}\n`;
    
    groupSummaries.forEach(s => {
      changelog += `- **${s.title}**: ${s.whatChanged.split('\n')[0]}\n`;
      if (s.linkedIssue) {
        changelog += `  - Linked Issue: #${s.linkedIssue}\n`;
      }
    });
    
    changelog += '\n';
  }

  return changelog;
}
